name: CI

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Solution_Name: Finance.NET.sln   
      Test_Project_Path: tests/Tests.csproj
      FORCE_COLOR: "true"
      DOTNET_LOGGING__CONSOLE__COLORBEHAVIOR: Enabled

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        

    - name: Install tools
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Restore
      run: dotnet restore 

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test with coverage
      env:
        FinanceNet__AlphaVantageApiKey: ${{ secrets.ALPHAVANTAGEAPIKEY }}
      run: |
        dotnet test "${{ env.Test_Project_Path }}" \
          --configuration Release \
          --no-build \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults/Tests \
          --logger "console;verbosity=detailed" \
          --filter "TestCategory!=Long-Running&FullyQualifiedName!~AlphaVantageTests"

    - name: Generate coverage report
      run: |
        reportgenerator \
          -reports:./TestResults/Tests/**/coverage.cobertura.xml \
          -targetdir:./TestResults/Reports \
          -reporttypes:"Html;lcov;Cobertura"

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        path-to-lcov: ./TestResults/Reports/lcov.info
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-coverage-report
        path: ./TestResults/Reports
